### ISSUE TITLE
Report generation limitation of single day's data representation

### ISSUE THREAD

**Issue by abhishekgupta-1** [sharmaeklavya2/showmylog#1]
Generated "report.html" shows the visualization of today's data. Enhance it to show the visualisation of past N's data logs.

**Comment by sharmaeklavya2** [comment]
It can display data for past days as well, you just need to feed the days you want as command-line arguments. Run `showmylog.py -h` for more information.

**Comment by sharmaeklavya2** [comment]
If you're using bash, you can use brace expansion: `showmylog.py {0..9}` will output a report for the past 10 days.

**Comment by abhishekgupta-1** [comment]
Thanks! :+1:
